rgtravelguide/config/routes.rb
Rails.application.routes.draw do
  get 'pages/login'

  resources :users

  get 'pages/about'

  root "destinations#index"
  resources :destinations

end

rgtravelguide/app/models/destination.rb
class Destination < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

rgtravelguide/app/models/user.rb
class User < ActiveRecord::Base
end

rgtravelguide/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rgtravelguide/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :image, :title, :post)
    end
end

rgtravelguide/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  
  def login
    @user = User.new
  end
end

rgtravelguide/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :from, :password)
    end
end

rgtravelguide/app/helpers/application_helper.rb
module ApplicationHelper
end

rgtravelguide/app/helpers/destinations_helper.rb
module DestinationsHelper
end

rgtravelguide/app/helpers/pages_helper.rb
module PagesHelper
end

rgtravelguide/app/helpers/users_helper.rb
module UsersHelper
end

rgtravelguide/app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
 <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:'form-control' %>
    </div>
 <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :post %><br>
    <%= f.text_area :post, rows: "10", class:'form-control'%>
  </div>
  <div class="actions row text-center">
        <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

rgtravelguide/app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

rgtravelguide/app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="row text-center">Destinations</h1>
</br>
<% if @destinations.any? %>
  <% @destinations.in_groups_of(3) do |group| %>
    <div class="row">
      <% group.compact.each do |destination| %>
        <div class="col-xs-4" style="margin-top: 20px;">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= link_to image_tag(destination.image_url, :width => '100%', :height => '200px'), destination if destination.image.present?%>
            </div>
            <div class="panel-footer">
              <h4 class="text-center"><%= link_to destination.name, destination %></h4>
              <p class="text-center"><%= destination.title %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% else  %>
   <p>No destinations found.</p>
<% end %>

rgtravelguide/app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

rgtravelguide/app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="margin:auto; width: 60%">
<h1 class=" text-center" style="margin-bottom: 30px;" >
  <strong><%= @destination.name %></strong>
</h1>

<p class="text-center">
  <%= image_tag(@destination.image_url, :width => 600) if @destination.image.present? %>
</p>

<h2 class="text-center">
  <strong><%= @destination.title %></strong>
</h2>

<p style="white-space: pre-line;">
  <%= @destination.post %>
</p>

<br/>

<p class="text-center">
  <%= link_to 'Edit', edit_destination_path(@destination) %> |
  <%= link_to 'Delete', @destination, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to 'Back', destinations_path %>
</p>
</div>

rgtravelguide/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rgtravelguide</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "RGTravelGuide", destinations_path, class: "navbar-brand" %>
      </div>
      <p class="navbar-text navbar-right">
  <%= link_to 'About', pages_about_path, class:'navbar-link' %>
</p>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Destinations", destinations_path %></li>
          <li><%= link_to 'Add New Destination', new_destination_path %></li>
          <li><%= link_to 'Users', new_user_path %></li>
        
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
      <%= yield %>
  </div>
  <footer class="footer">
    <div class="container">
      <p class="text-muted">Rails Girls KL 2017</p>
    </div>
  </footer>
</body>
</html>

rgtravelguide/app/views/pages/about.html.erb
<h1>About Me</h1>
<br>
<h2>
   Small girl in a big world
</h2>
<p>Find me in app/views/pages/about.html.erb</p>

rgtravelguide/app/views/pages/login.html.erb
<h1>Login</h1>
<p>Find me in app/views/pages/login.html.erb</p>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

rgtravelguide/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
<div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rgtravelguide/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rgtravelguide/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>From</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.from %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

rgtravelguide/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

rgtravelguide/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>From:</strong>
  <%= @user.from %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>